# Generated by Django 5.0.7 on 2024-11-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_add_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
