# Generated by Django 5.0.7 on 2024-11-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_add_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='webpage/images/'),
        ),
    ]
